upsample_rates: [ 4, 4, 2, 2, 2 ,2]
upsample_kernel_sizes: [8, 8, 4, 4, 4, 4 ]
upsample_initial_channel: 1536
resblock_kernel_sizes: [ 3,7,11 ]
resblock_dilation_sizes: [ [ 1,3,5 ], [ 1,3,5 ], [ 1,3,5 ] ]
discriminator_periods: [ 3, 5, 7, 11, 17, 23, 37 ]
use_tanh_at_final: false
use_bias_at_final: false
activation: "snakebeta"
snake_logscale: true
resblock: "1"
sampling_rate : 44100
num_mels: 128
num_freq: 1025
n_fft: 1024
hop_size: 256
win_size: 1024
fmin: 0
fmax: null